#!/usr/bin/python3

import sys

PRINT_LOCAL = True

SEGMENTS = {
    "CODE":     0xF000,
    "API":      0xF800,
    "APITABLE": 0xFF00,
    "ZEROPAGE": 0x0000,
    "STACK":    0x0100,
    "BSS":      0x0200,
}

print("XENLAB06")

for filename in sys.argv[1:]:
    f = open(filename)
    lines = f.readlines()
    
    label = "???"
    seg   = ""
    pc = 0
    
    for l in lines:
        if not (l[0] == '0'):
            continue
        
        src_a = int(l[:6], 16)
        src_s = l[24:].strip()
        #print(src_a, src_s)
        
        tokens = src_s.split()
        
        if (len(tokens) < 1):
            continue
        
        if tokens[0] == ".segment":
            tokens[1] = tokens[1].strip('"')
            seg = tokens[1]
            if seg in SEGMENTS:
                pc = SEGMENTS[seg]
            else:
                pc = pc + src_a
        if tokens[0] == ".zeropage":
            seg = "ZEROPAGE"
            pc = SEGMENTS[seg]
        elif seg != "":
            if tokens[0].endswith(":"):
                if tokens[0].startswith("@"):
                    if PRINT_LOCAL:
                        print((pc+src_a), "." + tokens[0][1:-1])
                    else:
                        print((pc+src_a), label + "." + tokens[0][1:-1])
                else:
                    label = tokens[0][:-1]
                    print((pc+src_a), label)
