#!/usr/bin/python3

import sys
import struct

PRINT_LOCAL = True

SEGMENTS = {
    "STUFF":     0xF000,
    "STUFF_EXT": 0xC000,
    "API":       0xF800,
    "APITABLE":  0xFF00,
    "ZEROPAGE":  0x0000,
    "STACK":     0x0100,
    "BSS":       0x0200,
}

out = sys.stdout.buffer

out.write(b"=P" + bytes([0] * 14))

for filename in sys.argv[1:]:
    f = open(filename)
    lines = f.readlines()
    
    label = "???"
    seg   = ""
    base_addr = 0
    
    for l in lines:
        if l[0] != '0':
            continue
        
        offset_addr = int(l[:6], 16)
        tokens = l[24:].strip().split()
        
        if (len(tokens) < 1):
            continue
        
        if tokens[0] == ".segment":
            tokens[1] = tokens[1].strip('"')
            seg = tokens[1]
            if seg in SEGMENTS:
                base_addr = SEGMENTS[seg]
            else:
                base_addr = base_addr + offset_addr
        
        elif seg != "":
            if tokens[0].endswith(":") and base_addr >= 0x8000:
                out.write(struct.pack("=H14s", (base_addr+offset_addr), bytes( tokens[0][:-1].encode('ascii') )))
